msgid ""
msgstr ""
"Project-Id-Version: red-discordbot\n"
"POT-Creation-Date: 2020-06-18 12:13+0000\n"
"Last-Translator: \n"
"Language-Team: German\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: redgettext 3.1\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Crowdin-Project: red-discordbot\n"
"X-Crowdin-Project-ID: 289505\n"
"X-Crowdin-Language: de\n"
"X-Crowdin-File-ID: 670\n"
"Language: de_DE\n"

#: redbot/cogs/audio/core/events/dpy.py:34
msgid "You have attempted to run Audio's Lavalink server on an unsupported architecture. Only settings related commands will be available."
msgstr "Du hast versucht, den Lavalink-Server von Audio auf einer nicht unterstützten Systemarchitektur auszuführen. Du kannst nur einstellungsbezogene Befehle verwenden."

#: redbot/cogs/audio/core/events/dpy.py:70
msgid "No DJ role found. Disabling DJ mode."
msgstr "Keine DJ-Rolle gefunden. DJ-Modus deaktiviert."

#: redbot/cogs/audio/core/events/dpy.py:80
msgid "`{user_input}` is not a valid value for `{command}`"
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:86
msgid "Unable To Parse Argument"
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:96
#: redbot/cogs/audio/core/events/dpy.py:104
msgid "Invalid Argument"
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:97
msgid "The argument you gave for `{}` is not valid: I was expecting a `{}`."
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:114
msgid "Invalid Environment"
msgstr "Ungültige Umgebung"

#: redbot/cogs/audio/core/events/dpy.py:115
msgid "Connection to Lavalink has been lost."
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:123
msgid "No Player Available"
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:124
msgid "The bot is not connected to a voice channel."
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:132
msgid "Unable to Get Track"
msgstr "Tracks können nicht abgerufen werden"

#: redbot/cogs/audio/core/events/dpy.py:133
msgid "I'm unable to get a track from Lavalink at the moment, try again in a few minutes."
msgstr ""

#: redbot/cogs/audio/core/events/lavalink.py:68
msgid "Couldn't get a valid track."
msgstr "Kein gültiger Track gefunden."

#: redbot/cogs/audio/core/events/lavalink.py:87
msgid "Auto Play started."
msgstr ""

#: redbot/cogs/audio/core/events/lavalink.py:102
msgid "Now Playing"
msgstr "Jetzt läuft"

#: redbot/cogs/audio/core/events/lavalink.py:104
msgid "Track length: {length} | Requested by: {user}"
msgstr "Länge des Tracks: {length} | Angefordert von: {user}"

#: redbot/cogs/audio/core/events/lavalink.py:125
msgid "Queue ended."
msgstr ""

#: redbot/cogs/audio/core/events/lavalink.py:167
msgid "Multiple Errors Detected"
msgstr ""

#: redbot/cogs/audio/core/events/lavalink.py:168
msgid "Closing the audio player due to multiple errors being detected. If this persists, please inform the bot owner as the Audio cog may be temporally unavailable."
msgstr "Der Audio-Player wird aufgrund mehrer Fehler geschlossen. Sollte das Problem vermehrt auftreten, informiere bitte den Besitzer des Bots, da das Audio-Cog eventuell vorübergehend nicht verfügbar ist."

#: redbot/cogs/audio/core/events/lavalink.py:182
msgid "Track Stuck"
msgstr "Der Track hat sich aufgehängt"

#: redbot/cogs/audio/core/events/lavalink.py:187
msgid "Track Error"
msgstr "Track-Fehler"

